version: "3.9"

services:
  database:
    container_name: lovelystay-database
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready -U ${POSTGRES_USER} -p 5432 -h ${POSTGRES_HOST} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    shm_size: 128mb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - lovelystay
  adminer:
    container_name: lovelystay-adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - lovelystay
    depends_on:
      - database

volumes:
  pgdata:
networks:
  lovelystay:
    driver: bridge
